#Deployment
###controllers/pb-deploy.tml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      name: emp-pod
      labels:
        app: employee-app
      
    spec:
      containers:
      - name: employee-management-container
        image: shubh1sinha/order-management:1.0
        resources:
          limits:
            cpu: '100m'
            memory: '1G'
          requests:
            cpu: '2m'
            memory: '400Mi'




